// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkmopejgtpqpppbycqkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrbW9wZWpndHBxcHBwYnljcWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjUxMTksImV4cCI6MjA2NDU0MTExOX0.r_90lv5q9Vo5oqNXy7oQA085FFNLMl5BnpPEisgT_4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);